
insert into public.site_sections(page_key,section_key,title,subtitle,content,sort_order,is_published) values
('home','hero','Hero','SOFTWARE · BANCA · FINTECH · INTEGRACIONES','{"eyebrow":"SOFTWARE · BANCA · FINTECH · INTEGRACIONES","line1":"Tecnología para","line2":"operaciones que no pueden fallar.","description":"Diseñamos e integramos soluciones de software para banca, fintech y empresas con operaciones críticas, combinando experiencia de negocio, arquitectura tecnológica y desarrollo de alto nivel.","primary_button":"Hablar con un especialista","secondary_button":"Explorar soluciones","metrics":[{"value":"20+","label":"Años de experiencia"},{"value":"Fintech","label":"Especialización"},{"value":"24/7","label":"Sistemas críticos"}]}'::jsonb,1,true),
('home','services_intro','Tecnología diseñada alrededor del negocio.','NUESTRAS CAPACIDADES','{"description":"Construimos plataformas confiables, escalables y preparadas para integrarse con ecosistemas empresariales complejos."}'::jsonb,2,true),
('home','expertise','Software construido con conocimiento de operaciones reales.','EXPERIENCIA FINANCIERA','{"description":"Una operación financiera debe ser consistente, conciliable, segura, auditable y resiliente."}'::jsonb,3,true)
on conflict(page_key,section_key) do update set title=excluded.title,subtitle=excluded.subtitle,content=excluded.content,sort_order=excluded.sort_order,is_published=excluded.is_published;

insert into public.services(slug,title,short_description,description,icon,tags,sort_order,is_published) values
('software-bancario','Software Bancario','Soluciones para ecosistemas financieros y operaciones críticas.','Diseño, desarrollo e integración de soluciones para banca digital, operaciones transaccionales y sistemas empresariales.','landmark',array['Core Banking','Banca Digital','Transacciones'],1,true),
('pagos-qr','Pagos y QR','Integración, procesamiento y conciliación de pagos QR.','Soluciones para generación, procesamiento, integración y conciliación de pagos y QR interoperable.','scan',array['QR','Pagos','Conciliación'],2,true),
('integraciones-api','Integraciones y APIs','Conectamos canales, sistemas legacy y plataformas modernas.','Diseño de APIs e integración REST/SOAP con sistemas internos y proveedores externos.','workflow',array['REST','SOAP','Integration'],3,true),
('onboarding-digital','Onboarding Digital','Automatización de alta, identidad y procesos digitales.','Flujos de onboarding con biometría, validación de identidad, aprobación y trazabilidad.','shield',array['Biometría','Identidad','Automatización'],4,true),
('software-empresarial','Software Empresarial','Plataformas a medida para procesos complejos.','Aplicaciones empresariales con arquitectura modular, seguridad y escalabilidad.','blocks',array['Enterprise','Web','Arquitectura'],5,true),
('modernizacion','Modernización Tecnológica','Evolución progresiva de aplicaciones legacy.','Modernización hacia arquitecturas y stacks actuales sin perder continuidad operacional.','wrench',array['Legacy','.NET','Cloud Ready'],6,true)
on conflict(slug) do update set title=excluded.title,short_description=excluded.short_description,description=excluded.description,icon=excluded.icon,tags=excluded.tags,sort_order=excluded.sort_order,is_published=excluded.is_published;
