import {useEffect,useState} from 'react'
import {ArrowRight,Database,QrCode,RefreshCw,Landmark,ScanLine,Workflow,ShieldCheck,Blocks,Wrench} from 'lucide-react'
import {Link} from 'react-router-dom'
import {supabase} from '../lib/supabase'
type Section={section_key:string;title:string;subtitle:string|null;content:any}
type Service={id:string;slug:string;title:string;short_description:string;icon:string|null;tags:string[]}
type Client={id:string;name:string;logo_url:string;website_url:string|null}
const iconMap:any={landmark:Landmark,scan:ScanLine,workflow:Workflow,shield:ShieldCheck,blocks:Blocks,wrench:Wrench}
const fallbackHero={eyebrow:'SOFTWARE · BANCA · FINTECH · INTEGRACIONES',line1:'Tecnología para',line2:'operaciones que no pueden fallar.',description:'Diseñamos e integramos soluciones de software para banca, fintech y empresas con operaciones críticas.',primary_button:'Hablar con un especialista',secondary_button:'Explorar soluciones',metrics:[{value:'20+',label:'Años de experiencia'},{value:'Fintech',label:'Especialización'},{value:'24/7',label:'Sistemas críticos'}]}
export default function HomePage(){const[sections,setSections]=useState<Record<string,Section>>({});const[services,setServices]=useState<Service[]>([]);const[clients,setClients]=useState<Client[]>([])
useEffect(()=>{supabase.from('site_sections').select('*').eq('page_key','home').eq('is_published',true).order('sort_order').then(({data})=>setSections(Object.fromEntries((data||[]).map((s:any)=>[s.section_key,s]))));supabase.from('services').select('*').eq('is_published',true).order('sort_order').then(({data})=>setServices(data||[]));supabase.from('clients').select('id,name,logo_url,website_url').eq('is_published',true).not('logo_url','is',null).neq('logo_url','').order('sort_order').then(({data,error})=>{if(!error)setClients((data||[]) as Client[])})},[])
const h={...fallbackHero,...(sections.hero?.content||{})}
return <><section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span/>{h.eyebrow}</div><h1>{h.line1}<span>{h.line2}</span></h1><p>{h.description}</p><div className="hero-actions"><Link className="button button-primary" to="/contacto">{h.primary_button}<ArrowRight size={18}/></Link><Link className="button button-secondary" to="/soluciones">{h.secondary_button}</Link></div><div className="metrics">{h.metrics.map((m:any)=><div className="metric" key={m.label}><strong>{m.value}</strong><span>{m.label}</span></div>)}</div></div>
<div className="architecture-visual"><div className="float-card float-top"><strong>Integraciones seguras</strong><span>APIs · Servicios · Canales</span></div><div className="tech-card"><div className="tech-window"><div className="window-dots"><i/><i/><i/></div><div className="online">● PLATFORM ONLINE</div></div><div className="tech-content"><div className="tech-label">FINANCIAL TECHNOLOGY ARCHITECTURE</div><div className="channel-row"><div><strong>Mobile Banking</strong><span>Digital Channel</span></div><div><strong>Internet Banking</strong><span>Digital Channel</span></div></div><div className="connector"/><div className="api-layer"><strong>API & Integration Layer</strong><span>Security · Orchestration · Transactions</span></div><div className="connector"/><div className="core-row"><div><Database/><strong>CORE</strong><span>Banking</span></div><div><QrCode/><strong>QR</strong><span>Payments</span></div><div><RefreshCw/><strong>APIs</strong><span>Integration</span></div></div></div></div></div></div></section>
{clients.length>0&&<section className="clients-band" aria-label="Clientes"><div className="container"><span className="section-kicker">EMPRESAS QUE CONFÍAN EN ARPAL SOFT</span><div className="client-logos">{clients.map(c=>{const logo=<img src={c.logo_url} alt={c.name} loading="lazy"/>;return c.website_url?<a key={c.id} href={c.website_url} target="_blank" rel="noreferrer" title={c.name}>{logo}</a>:<div key={c.id} title={c.name}>{logo}</div>})}</div></div></section>}
<section className="section"><div className="container"><div className="section-heading"><span className="section-kicker">{sections.services_intro?.subtitle||'NUESTRAS CAPACIDADES'}</span><h2>{sections.services_intro?.title||'Tecnología diseñada alrededor del negocio.'}</h2><p>{sections.services_intro?.content?.description||'Construimos plataformas confiables, escalables y preparadas para ecosistemas complejos.'}</p></div><div className="service-grid">{services.map(s=>{const Icon=iconMap[s.icon||'blocks']||Blocks;return <article className="service-card" key={s.id}><div className="service-icon"><Icon/></div><h3>{s.title}</h3><p>{s.short_description}</p><div className="tags">{s.tags?.map(t=><span key={t}>{t}</span>)}</div></article>})}</div></div></section>
<section className="section expertise" id="experiencia"><div className="container expertise-grid"><div className="section-heading"><span className="section-kicker">{sections.expertise?.subtitle||'EXPERIENCIA FINANCIERA'}</span><h2>{sections.expertise?.title||'Software construido con conocimiento de operaciones reales.'}</h2><p>{sections.expertise?.content?.description||'Consistencia, seguridad, auditoría, integración y resiliencia desde el diseño.'}</p></div><div className="principles-grid">{['Seguridad','Disponibilidad','Consistencia','Auditoría','Integración','Escalabilidad'].map(x=><div className="principle" key={x}><ShieldCheck/><div><strong>{x}</strong><span>Diseño empresarial orientado a procesos críticos.</span></div></div>)}</div></div></section>
<section className="section" id="tecnologia"><div className="container"><div className="section-heading centered"><span className="section-kicker">STACK TECNOLÓGICO</span><h2>Tecnología moderna. Criterio empresarial.</h2></div><div className="tech-groups">{[['BACKEND','.NET','C#','Java','REST APIs'],['FRONTEND','React','Vue','TypeScript','Responsive UI'],['DATOS','SQL Server','PostgreSQL','Supabase','Data APIs'],['ARQUITECTURA','Microservices','Integration','CI/CD','Cloud Ready']].map(g=><div className="tech-group" key={g[0]}><span>{g[0]}</span>{g.slice(1).map(x=><strong key={x}>{x}</strong>)}</div>)}</div></div></section>
<section className="section"><div className="container"><div className="cta-panel"><div><span className="section-kicker">HABLEMOS DE TU PROYECTO</span><h2>¿Tu operación necesita tecnología que acompañe el negocio?</h2><p>Conversemos sobre el problema, la arquitectura y el camino más eficiente para resolverlo.</p></div><Link className="button button-primary" to="/contacto">Contactar a ARPAL SOFT <ArrowRight size={18}/></Link></div></div></section></>}
