import {Outlet,Link,NavLink} from 'react-router-dom'
import {Menu,Moon,Sun,X} from 'lucide-react'
import {useEffect,useState} from 'react'
import {LocaleProvider,useLang,useRoutes,routes} from '../lib/locale'
import PageViewTracker from './PageViewTracker'
type Theme='warm'|'dark'
const labels={es:{solutions:'Soluciones',commercial:'Servicios digitales',experience:'Experiencia',technology:'Tecnología',about:'Nosotros',contact:'Contáctanos',talk:'¿Hablamos?',communicate:'Comunícate con nosotros',company:'Empresa',specialization:'Especialización',banking:'Software bancario',integrations:'Integraciones',tagline:'Tecnología empresarial para operaciones críticas.',rights:'Todos los derechos reservados.'},en:{solutions:'Solutions',commercial:'Digital services',experience:'Experience',technology:'Technology',about:'About us',contact:'Contact us',talk:"Let's talk",communicate:'Talk to our team',company:'Company',specialization:'Expertise',banking:'Banking software',integrations:'Integrations',tagline:'Enterprise technology for mission-critical operations.',rights:'All rights reserved.'},pt:{solutions:'Soluções',commercial:'Serviços digitais',experience:'Experiência',technology:'Tecnologia',about:'Sobre nós',contact:'Fale conosco',talk:'Vamos conversar?',communicate:'Fale com nossa equipe',company:'Empresa',specialization:'Especialização',banking:'Software bancário',integrations:'Integrações',tagline:'Tecnologia empresarial para operações críticas.',rights:'Todos os direitos reservados.'}}
function Brand(){return <img className="brand-logo" src="/arpalsoft-logo.png" alt="ARPAL SOFT — Soluciones que conectan"/>}
function Header({theme,onTheme}:{theme:Theme;onTheme:()=>void}){const[open,setOpen]=useState(false);const lang=useLang(),r=useRoutes(),l=labels[lang];return <header className="site-header"><div className="container navbar"><Link to={r.home} className="brand" onClick={()=>setOpen(false)}><Brand/></Link><button className="menu-button" aria-label="Abrir menú" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'main-nav open':'main-nav'}><NavLink to={r.solutions}>{l.solutions}</NavLink><NavLink className="commercial-nav" to={r.commercial} onClick={()=>setOpen(false)}>{l.commercial}</NavLink><a href={`${r.home}#experiencia`}>{l.experience}</a><NavLink to={r.about}>{l.about}</NavLink><div className="language-switch" aria-label="Idioma"><Link className={lang==='es'?'active':''} to={routes.es.home}>ES</Link><Link className={lang==='en'?'active':''} to={routes.en.home}>EN</Link><Link className={lang==='pt'?'active':''} to={routes.pt.home}>PT</Link></div><button className="theme-switch" onClick={onTheme} aria-label={`Cambiar tema`}>{theme==='warm'?<Moon/>:<Sun/>}<span>{theme==='warm'?'Dark':'Warm'}</span></button><NavLink className="nav-cta" to={r.contact} onClick={()=>setOpen(false)}>{l.contact}</NavLink></nav></div></header>}
function Footer(){const lang=useLang(),r=useRoutes(),l=labels[lang];return <footer className="footer"><div className="container footer-grid"><div><div className="brand"><Brand/></div><p>{l.tagline}</p></div><div><strong>{l.company}</strong><Link to={r.about}>{l.about}</Link><Link to={r.solutions}>{l.solutions}</Link><Link to={r.contact}>{l.contact}</Link></div><div><strong>{l.specialization}</strong><span>{l.banking}</span><span>Fintech</span><span>{l.integrations}</span></div></div><div className="container footer-bottom">© {new Date().getFullYear()} ARPAL SOFT. {l.rights}</div></footer>}
function PublicLayout(){const[theme,setTheme]=useState<Theme>(()=>localStorage.getItem('arpal-theme')==='dark'?'dark':'warm');const lang=useLang(),r=useRoutes(),l=labels[lang];useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.lang=lang;localStorage.setItem('arpal-theme',theme)},[theme,lang]);return <><PageViewTracker/><div className="background-grid"/><Header theme={theme} onTheme={()=>setTheme(t=>t==='warm'?'dark':'warm')}/><main><Outlet/></main><Link className="floating-contact" to={r.contact} aria-label={l.communicate}><span>{l.talk}</span><strong>{l.communicate}</strong></Link><Footer/></>}
export default function SiteLayout(){return <LocaleProvider><PublicLayout/></LocaleProvider>}
