-- Estadísticas de visitas y obligatoriedad de MFA para el administrador.
create table if not exists public.page_views(
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  path text not null check(char_length(path) between 1 and 500),
  page_title text check(char_length(page_title) <= 300),
  referrer text check(char_length(referrer) <= 1000),
  language text check(char_length(language) <= 12),
  device_type text not null default 'desktop' check(device_type in ('mobile','tablet','desktop')),
  created_at timestamptz not null default now()
);
create index if not exists page_views_created_at_idx on public.page_views(created_at desc);
create index if not exists page_views_path_idx on public.page_views(path);
create index if not exists page_views_session_idx on public.page_views(session_id);
alter table public.page_views enable row level security;
drop policy if exists "public records page views" on public.page_views;
create policy "public records page views" on public.page_views for insert to anon,authenticated with check(char_length(path) between 1 and 500 and device_type in ('mobile','tablet','desktop'));
drop policy if exists "aal2 admins read page views" on public.page_views;
create policy "aal2 admins read page views" on public.page_views for select to authenticated using(public.is_admin() and coalesce(auth.jwt()->>'aal','aal1')='aal2');
grant insert on public.page_views to anon,authenticated;
grant select on public.page_views to authenticated;
grant usage,select on sequence public.page_views_id_seq to anon,authenticated;
drop policy if exists "mfa protects admin membership" on public.admin_users;
create policy "mfa protects admin membership" on public.admin_users as restrictive for select to authenticated using(coalesce(auth.jwt()->>'aal','aal1')='aal2');
drop policy if exists "mfa protects section writes" on public.site_sections;
create policy "mfa protects section writes" on public.site_sections as restrictive for all to authenticated using(coalesce(auth.jwt()->>'aal','aal1')='aal2') with check(coalesce(auth.jwt()->>'aal','aal1')='aal2');
drop policy if exists "mfa protects service writes" on public.services;
create policy "mfa protects service writes" on public.services as restrictive for all to authenticated using(coalesce(auth.jwt()->>'aal','aal1')='aal2') with check(coalesce(auth.jwt()->>'aal','aal1')='aal2');
drop policy if exists "mfa protects contact administration" on public.contact_messages;
create policy "mfa protects contact administration" on public.contact_messages as restrictive for select to authenticated using(coalesce(auth.jwt()->>'aal','aal1')='aal2');
drop policy if exists "mfa protects contact updates" on public.contact_messages;
create policy "mfa protects contact updates" on public.contact_messages as restrictive for update to authenticated using(coalesce(auth.jwt()->>'aal','aal1')='aal2') with check(coalesce(auth.jwt()->>'aal','aal1')='aal2');
do $$ begin if to_regclass('public.clients') is not null then execute 'drop policy if exists "mfa protects client writes" on public.clients'; execute 'create policy "mfa protects client writes" on public.clients as restrictive for all to authenticated using (coalesce(auth.jwt()->>''aal'',''aal1'')=''aal2'') with check (coalesce(auth.jwt()->>''aal'',''aal1'')=''aal2'')'; end if; end $$;


