import {useEffect,useMemo,useState} from 'react'
import {Download,Eye,MonitorSmartphone,Users} from 'lucide-react'
import {supabase} from '../../lib/supabase'
type View={session_id:string;path:string;page_title:string|null;referrer:string|null;language:string|null;device_type:string;created_at:string}
const dayKey=(d:Date)=>d.toISOString().slice(0,10)
export default function AdminDashboardPage(){
 const[content,setContent]=useState({sections:0,services:0,contacts:0}),[views,setViews]=useState<View[]>([]),[period,setPeriod]=useState(30),[error,setError]=useState('')
 useEffect(()=>{void load()},[period])
 async function load(){setError('');const since=new Date(Date.now()-period*86400000).toISOString();const[a,b,c,v]=await Promise.all([supabase.from('site_sections').select('*',{count:'exact',head:true}),supabase.from('services').select('*',{count:'exact',head:true}),supabase.from('contact_messages').select('*',{count:'exact',head:true}).eq('status','new'),supabase.from('page_views').select('session_id,path,page_title,referrer,language,device_type,created_at').gte('created_at',since).order('created_at',{ascending:true}).limit(10000)]);setContent({sections:a.count||0,services:b.count||0,contacts:c.count||0});if(v.error)setError('Aplica la migración de estadísticas en Supabase para comenzar a registrar visitas.');else setViews((v.data||[]) as View[])}
 const metrics=useMemo(()=>{const unique=new Set(views.map(v=>v.session_id)).size,pages=new Map<string,number>(),devices=new Map<string,number>();for(const v of views){pages.set(v.path,(pages.get(v.path)||0)+1);devices.set(v.device_type,(devices.get(v.device_type)||0)+1)}const top=[...pages].sort((a,b)=>b[1]-a[1]).slice(0,8);const days:Array<[string,number]>=[];for(let i=period-1;i>=0;i--){const d=new Date(Date.now()-i*86400000),key=dayKey(d);days.push([key,views.filter(v=>v.created_at.slice(0,10)===key).length])}return{unique,top,days,devices:[...devices].sort((a,b)=>b[1]-a[1]),max:Math.max(1,...days.map(d=>d[1]))}},[views,period])
 async function exportCsv(){const all:View[]=[];for(let from=0;;from+=1000){const{data,error}=await supabase.from('page_views').select('session_id,path,page_title,referrer,language,device_type,created_at').order('created_at',{ascending:false}).range(from,from+999);if(error)return setError(error.message);all.push(...(data as View[]));if(!data||data.length<1000)break}const esc=(x:unknown)=>`"${String(x??'').replace(/"/g,'""')}"`,csv=['fecha,sesion,ruta,titulo,referencia,idioma,dispositivo',...all.map(v=>[v.created_at,v.session_id,v.path,v.page_title,v.referrer,v.language,v.device_type].map(esc).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`arpalsoft-visitas-${dayKey(new Date())}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <><div className="admin-header admin-header-inline"><div><span>ANALÍTICA</span><h1>Estadísticas de visitas</h1></div><div className="analytics-actions"><select value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value={7}>7 días</option><option value={30}>30 días</option><option value={90}>90 días</option></select><button className="button button-secondary" onClick={exportCsv}><Download/>Descargar CSV</button></div></div>{error&&<div className="analytics-notice">{error}</div>}<div className="admin-stats analytics-stats"><div><Eye/><strong>{views.length}</strong><span>Vistas</span></div><div><Users/><strong>{metrics.unique}</strong><span>Visitantes únicos</span></div><div><MonitorSmartphone/><strong>{views.length?Math.round(views.length/Math.max(metrics.unique,1)*10)/10:0}</strong><span>Páginas por visita</span></div><div><strong>{content.contacts}</strong><span>Mensajes nuevos</span></div></div><div className="analytics-grid"><section className="admin-panel analytics-chart"><h2>Visitas por día</h2><div className="bar-chart">{metrics.days.map(([day,count])=><div className="bar-column" key={day} title={`${day}: ${count}`}><span>{count||''}</span><i style={{height:`${Math.max(3,count/metrics.max*100)}%`}}/><small>{period<=7?day.slice(5):day.endsWith('-01')?day.slice(5):''}</small></div>)}</div></section><section className="admin-panel"><h2>Páginas más visitadas</h2><div className="analytics-list">{metrics.top.length?metrics.top.map(([path,count])=><div key={path}><span>{path}</span><strong>{count}</strong></div>):<p>Aún no hay visitas registradas.</p>}</div></section><section className="admin-panel"><h2>Dispositivos</h2><div className="analytics-list">{metrics.devices.map(([device,count])=><div key={device}><span>{device==='mobile'?'Móvil':device==='tablet'?'Tablet':'Escritorio'}</span><strong>{Math.round(count/Math.max(views.length,1)*100)}%</strong></div>)}</div></section><section className="admin-panel"><h2>Contenido</h2><div className="analytics-list"><div><span>Secciones</span><strong>{content.sections}</strong></div><div><span>Servicios</span><strong>{content.services}</strong></div></div></section></div></>
}
