import {FormEvent,useEffect,useRef,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {ShieldCheck} from 'lucide-react'
import {supabase} from '../../lib/supabase'
type Step='email'|'sent'|'challenge'|'enroll'
type Enrollment={id:string;qr:string;secret:string}
export default function AdminLoginPage(){
 const n=useNavigate(),preparing=useRef(false),[step,setStep]=useState<Step>('email'),[email,setEmail]=useState(''),[factorId,setFactorId]=useState(''),[enrollment,setEnrollment]=useState<Enrollment|null>(null),[e,setE]=useState(''),[l,setL]=useState(false),[recovering,setRecovering]=useState(window.location.hash.includes('access_token')||window.location.search.includes('code='))
 useEffect(()=>{document.body.classList.add('admin-auth-page');const{data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(session&&(event==='SIGNED_IN'||event==='INITIAL_SESSION'||event==='TOKEN_REFRESHED'))window.setTimeout(()=>void prepareMfa(),0)});void supabase.auth.getSession().then(({data})=>{if(data.session)void prepareMfa();else setRecovering(false)});return()=>{subscription.unsubscribe();document.body.classList.remove('admin-auth-page')}},[])
 async function prepareMfa(){if(preparing.current)return;preparing.current=true;setRecovering(true);setE('');try{const{data:aal}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal?.currentLevel==='aal2'){n('/admin');return}const{data:admin}=await supabase.rpc('is_admin');if(!admin){await supabase.auth.signOut();setStep('email');setE('Este correo no está registrado como administrador activo.');return}const{data,error}=await supabase.auth.mfa.listFactors();if(error){setE(error.message);return}const verified=data?.totp?.find((f:any)=>f.status==='verified');if(verified){setFactorId(verified.id);setStep('challenge');return}const pending=data?.totp?.find((f:any)=>f.status==='unverified');if(pending)await supabase.auth.mfa.unenroll({factorId:pending.id});const{data:enrolled,error:enrollError}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'ARPALSOFT Admin',issuer:'ARPALSOFT'});if(enrollError){setE(enrollError.message);return}setEnrollment({id:enrolled.id,qr:enrolled.totp.qr_code,secret:enrolled.totp.secret});setFactorId(enrolled.id);setStep('enroll')}finally{preparing.current=false;setRecovering(false)}}
 async function requestAccess(ev:FormEvent<HTMLFormElement>){ev.preventDefault();setL(true);setE('');const value=String(new FormData(ev.currentTarget).get('email')).trim().toLowerCase();const{data:allowed,error:checkError}=await supabase.rpc('is_registered_admin_email',{p_email:value});if(checkError||!allowed){setL(false);return setE('Este correo no está registrado como administrador activo.')}const{error}=await supabase.auth.signInWithOtp({email:value,options:{shouldCreateUser:false,emailRedirectTo:`${window.location.origin}/admin/login`}});setL(false);if(error)return setE('No pudimos enviar el enlace. Intenta nuevamente en unos minutos.');setEmail(value);setStep('sent')}
 async function verify(ev:FormEvent<HTMLFormElement>){ev.preventDefault();setL(true);setE('');const code=String(new FormData(ev.currentTarget).get('code')).replace(/\D/g,'');const{error}=await supabase.auth.mfa.challengeAndVerify({factorId,code});if(error){setE('El código no es válido o ha vencido.');return setL(false)}n('/admin')}
 return <div className="admin-login"><div className="admin-auth-glow admin-auth-glow-one"/><div className="admin-auth-glow admin-auth-glow-two"/><form onSubmit={step==='email'?requestAccess:step==='sent'?e=>e.preventDefault():verify}><div className="admin-auth-badge"><ShieldCheck/>Acceso protegido</div><div className="brand"><img src="/arpalsoft-logo.png" alt="ARPAL SOFT"/></div>{recovering?<div className="auth-recovering"><span/><h1>Validando enlace seguro</h1><p>Estamos recuperando tu sesión y preparando Google Authenticator.</p></div>:step==='email'?<><h1>Panel administrativo</h1><p className="admin-auth-intro">Ingresa con un correo autorizado. No usamos contraseñas: recibirás un enlace de acceso y luego verificarás Google Authenticator.</p><label>Correo Gmail autorizado<input type="email" name="email" autoComplete="email" placeholder="nombre@gmail.com" required/></label><button className="button button-primary" disabled={l}>{l?'Enviando enlace...':'Enviar enlace de acceso'}</button><div className="admin-auth-steps"><span><b>1</b>Correo autorizado</span><span><b>2</b>Enlace seguro</span><span><b>3</b>Authenticator</span></div></>:step==='sent'?<><div className="mfa-title"><ShieldCheck/><div><h1>Revisa tu correo</h1><p>Enviamos un enlace seguro a <strong>{email}</strong>. Ábrelo en este mismo navegador para continuar.</p></div></div><div className="admin-auth-tip">Si no aparece en unos minutos, revisa Spam o Correo no deseado.</div><button type="button" className="button button-secondary" onClick={()=>setStep('email')}>Usar otro correo</button></>:<><div className="mfa-title"><ShieldCheck/><div><h1>{step==='enroll'?'Registra Google Authenticator':'Google Authenticator'}</h1><p>{step==='enroll'?'Escanea el QR una sola vez y confirma el primer código.':'Escribe el código de seis dígitos de tu aplicación.'}</p></div></div>{step==='enroll'&&enrollment&&<div className="mfa-enrollment"><img src={enrollment.qr} alt="Código QR para Google Authenticator"/><span>Clave manual</span><code>{enrollment.secret}</code></div>}<label>Código de 6 dígitos<input className="mfa-code" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required autoFocus/></label><button className="button button-primary" disabled={l}>{l?'Verificando...':step==='enroll'?'Registrar y entrar':'Entrar al administrador'}</button><button type="button" className="admin-link-button" onClick={async()=>{await supabase.auth.signOut();setStep('email');setEnrollment(null);setE('')}}>Cerrar esta verificación</button></>}{e&&<div className="admin-error">{e}</div>}</form></div>
}
