import {FormEvent,useEffect,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {ShieldCheck} from 'lucide-react'
import {supabase} from '../../lib/supabase'
type Step='password'|'challenge'|'enroll'
type Enrollment={id:string;qr:string;secret:string}
export default function AdminLoginPage(){
 const n=useNavigate(),[step,setStep]=useState<Step>('password'),[factorId,setFactorId]=useState(''),[enrollment,setEnrollment]=useState<Enrollment|null>(null),[e,setE]=useState(''),[l,setL]=useState(false)
 useEffect(()=>{void (async()=>{const{data:{user}}=await supabase.auth.getUser();if(user)await prepareMfa()})()},[])
 async function prepareMfa(){const{data:aal}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal?.currentLevel==='aal2')return n('/admin');const{data:admin}=await supabase.rpc('is_admin');if(!admin){await supabase.auth.signOut();setStep('password');return setE('El usuario no tiene permisos de administrador.')}const{data,error}=await supabase.auth.mfa.listFactors();if(error)return setE(error.message);const verified=data?.totp?.find((f:any)=>f.status==='verified');if(verified){setFactorId(verified.id);setStep('challenge');return}const{data:enrolled,error:enrollError}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'ARPALSOFT Admin',issuer:'ARPALSOFT'});if(enrollError)return setE(enrollError.message);setEnrollment({id:enrolled.id,qr:enrolled.totp.qr_code,secret:enrolled.totp.secret});setFactorId(enrolled.id);setStep('enroll')}
 async function login(ev:FormEvent<HTMLFormElement>){ev.preventDefault();setL(true);setE('');const f=new FormData(ev.currentTarget);const{error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error){setE('Credenciales incorrectas.');return setL(false)}await prepareMfa();setL(false)}
 async function verify(ev:FormEvent<HTMLFormElement>){ev.preventDefault();setL(true);setE('');const code=String(new FormData(ev.currentTarget).get('code')).replace(/\D/g,'');const{error}=await supabase.auth.mfa.challengeAndVerify({factorId,code});if(error){setE('El código no es válido o ha vencido.');return setL(false)}n('/admin')}
 return <div className="admin-login"><form onSubmit={step==='password'?login:verify}><div className="brand"><img src="/logo.svg" alt="ARPAL SOFT"/><span><strong>ARPAL SOFT</strong><small>ACCESO SEGURO</small></span></div>{step==='password'?<><h1>Administración</h1><p>Ingresa con tus credenciales. Después verificaremos Google Authenticator.</p><label>Email<input type="email" name="email" autoComplete="username" required/></label><label>Contraseña<input type="password" name="password" autoComplete="current-password" required/></label><button className="button button-primary" disabled={l}>{l?'Validando...':'Continuar'}</button></>:<><div className="mfa-title"><ShieldCheck/><div><h1>{step==='enroll'?'Activa Google Authenticator':'Verificación en dos pasos'}</h1><p>{step==='enroll'?'Escanea el QR y confirma el primer código.':'Escribe el código de seis dígitos de tu aplicación.'}</p></div></div>{step==='enroll'&&enrollment&&<div className="mfa-enrollment"><img src={enrollment.qr} alt="Código QR para Google Authenticator"/><span>Clave manual</span><code>{enrollment.secret}</code></div>}<label>Código de 6 dígitos<input className="mfa-code" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required autoFocus/></label><button className="button button-primary" disabled={l}>{l?'Verificando...':step==='enroll'?'Activar y entrar':'Verificar y entrar'}</button><button type="button" className="admin-link-button" onClick={async()=>{await supabase.auth.signOut();setStep('password');setEnrollment(null);setE('')}}>Volver al acceso</button></>}{e&&<div className="admin-error">{e}</div>}</form></div>
}
